### ISSUE TITLE
Error: Fail to get CSRF token with err ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by artdias90** [adobe/aem-upload#109]
### Expected Behaviour
after uploading an asset with aem-upload to a specific AEM assets folder, the file should be uploaded

### Actual Behaviour
after calling aem-upload, detailed result contains error: Fail to get CSRF token with err ReferenceError: setImmediate is not defined

#### Platform and Version
latest AEM SDK from 06.2023  (problem also on earlier SDK versions)
using "@adobe/aem-upload" 2.0.1

#### Logs taken while reproducing problem
```
[
    {
        "fileUrl": "http://localhost:4502/content/dam/uploaded-images/XYZ/image-2023-05-08-16-36-45-656.png",
        "fileSize": 42897,
        "blob": "<provided>",
        "result": {
            "fileName": "image-2023-05-08-16-36-45-656.png",
            "fileSize": 42897,
            "targetFolder": "/content/dam/uploaded-images/XYZ",
            "targetFile": "/content/dam/uploaded-images/XYZ/image-2023-05-08-16-36-45-656.png",
            "sourceFolder": "/",
            "sourceFile": "//",
            "errors": [
                {
                    "message": "Fail to get CSRF token with err ReferenceError: setImmediate is not defined",
                    "code": "EUNKNOWN",
                    "innerStack": "Error: Fail to get CSRF token with err ReferenceError: setImmediate is not defined\n    at XYZ.min.js:2:336268\n    at Generator.throw (<anonymous>)\n    at r (XYZ.min.js:2:335661)\n    at c XYZ.min.js:2:335900)"
                }
            ]
        }
    }
]
```

I can see the image on browser, but it is not uploaded to the desired folder. tested on localhost and also on a Sandbox Environment.

**Comment by mfrisbey** [comment]
Will you please provide sample code that can reproduce the problem?

**Comment by EsteBustamante** [comment]
It's most likely because you are not authorized. Your author instance will require a CSRF token. You should add an authentication method like the one below:
`.withHeaders({
            Authorization: 'your type of authentication'
        });`

**Comment by artdias90** [comment]
Thank you, we can close the issue.
