### ISSUE TITLE
Basic authentication example is missing scheme

### ISSUE THREAD

**Issue by mreutegg** [adobe/aem-upload#121]
### Expected Behaviour

Using basic authentication example shows in README.md should work.

### Actual Behaviour

Requests are not authorized.

### Reproduce Scenario (including but not limited to)

Run the [example script](https://github.com/adobe/aem-upload/blame/f8fb089887fec8515878f0c5227dc2ef5a431f6a/README.md#L312-L333) in README.md targeting a local AEM.

**Comment by mfrisbey** [comment]
Thanks for the report and contribution +1
