### ISSUE TITLE
Please indicate which AEM version is required

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-upload#19]
It isn't clear if this tool supports AEM 6.5 (either on-prem or hosted on AMS) or requires AEM as a CloudService. The first sentence of the README makes me think that AEMaaCS is required, 

```
In legacy AEM Assets, a single post request to createAsset servlet is enough for uploading files. Newer versions of AEM use direct binary access, which requires a more involved algorithm
```

but it is never explicitly mentioned.

Reference: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/assent-api-upload-error/qaq-p/370607/comment-id/77352#M77352

**Comment by ireasor** [comment]
This tool was built to make it easier to upload assets to an AEM as a Cloud Service environment.  It would not work against an AEM 6.5 environment.

**Comment by mfrisbey** [comment]
@joerghoh Unfortunately the tool depends on a configuration, so it's not as simple as listing a version number or host location. However, I've updated the first paragraph to hopefully help clarify this. Feel free to take a look and let us know if this helps with the confusion.
