### ISSUE TITLE
Upload all files in a folder recursively

### ISSUE THREAD

**Issue by jbenn313** [adobe/aem-upload#20]
This tool would be even more useful if it could upload all folder contents recursively.

Suggestion: Support a new property in the _Upload files_ array of type String with the name _folderPath_.  If _folderPath_ is specified then _fileName_, _fileSize_, _filePath_, and _blob_ are ignored.  The other _Upload files_ parameters are honored.  When _folderPath_ is specified the program uploads all files at the _folderPath_ location, and then does the same for all child folders at the _folderPath_ location, and so on recursively.

**Comment by jbenn313** [comment]
Hi @mfrisbey.  In https://jira.corp.adobe.com/browse/CQ-4303877 you mention "Moving the folder upload logic from AEM Desktop's code into aem-upload".  Please could you help us locate that AEM Desktop code? Also we are open to any advice you may have that would ensure the code we write here makes an acceptable PR.  Thanks.

**Comment by mfrisbey** [comment]
This has been implemented in v1.20.0. See newly added `withDeepUpload()` option in [FileSystemUploadOptions](https://github.com/adobe/aem-upload#supported-file-options).
