### ISSUE TITLE
aem-upload from behind proxy

### ISSUE THREAD

**Issue by pmckeen** [adobe/aem-upload#35]
### Expected Behaviour
aem-upload supports specification and/or autodetection of proxy configuration.

### Actual Behaviour
aem-upload times out when attempting to upload from an environment with proxy requirement.

### Reproduce Scenario (including but not limited to)
Windows host with Proxy requirement
Windows host with Fiddler or equivalent, monitoring for traffic via proxy to AEM Cloud.

#### Steps to Reproduce
Configure host machine to block default traffic and require http proxy or set up dev monitorable proxy (Fiddler, etc)
Attempt aem-upload to cloud.
Upload will time out or bypass proxy.

#### Platform and Version
Windows hosts, any AEMaaCS

#### Sample Code that illustrates the problem
Any upload script that works in a non-proxy environment

#### Logs taken while reproducing problem
2021-02-02T16:18:48.319Z [] error: Error while Uploading Error: connect ETIMEDOUT [[redacted]]:443

**Comment by mfrisbey** [comment]
Thank you for the issue report, I can confirm that this is an issue. A potential resolution would be to add a new `withProxy()` method to `DirectBinaryUploadOptions`, and ensure this value is passed through to the `proxy` option when submitting requests with [axios](https://www.npmjs.com/package/axios).

No ETA for a fix at the moment, but we do accept PRs if a fix is required sooner.

**Comment by pmckeen** [comment]
Axios does respect environment variables for proxy, so that is potentially
an option worth documenting. For authenticated proxies, from what I can
tell, this requires a plaintext password in the environment variable, which
is a potential security risk.

**Comment by mfrisbey** [comment]
Version 1.3.0 has introduced a `withProxy()` option to `DirectBinaryUploadOptions`. When specified, all requests sent by the library will go through the specified proxy.
