### ISSUE TITLE
Unable to upload to local AEM using FileSystemUploadOptions

### ISSUE THREAD

**Issue by leachuk** [adobe/aem-upload#53]
### Expected Behaviour
**Note.** I understand this code is designed to upload to the new adobe IO architecture of AEM Cloud, however, I'm assuming I can still use it to upload to none AEM Cloud versions, and local AEM SDK versions, using the `FileSystemUploadOptions` configuration. This isn't explicitly detailed however, I'm inferring the behaviour from the naming of `DirectBinaryUploadOptions` vs `FileSystemUploadOptions`. If this assumption is false, guidance on if and how it might be possible to work around this AEM Cloud requirement would be much appreciated. 

I'm trying to follow the example at https://github.com/adobe/aem-upload#uploading-local-files with the `aio-cli-plugin-aem`.

After updating the source in `aio-cli-plugin-aem` to use the `FileSystemUploadOptions` provided by v1.0.20 of this repo and calling the command with an image passed as an argument, I expect the file to be uploaded into my local AEM (and I'm assuming none AEM Cloud versions, like AEM 6.5)

E.g. running from the root of the adobe/aio-cli-plugin-aem repo
```
node bin/run aem:upload -h http://localhost:4502 -c admin:admin IMAGE_27547.jpg
```

### Actual Behaviour
The default folder is created at the root of /content/dam, but no image has been uploaded.

#### Steps to Reproduce
- Check out the repo https://github.com/adobe/aio-cli-plugin-aem
- Update package.json `dependencies` to latest`"@adobe/aem-upload": "1.0.20"`
- run `npm install`
- Update the source file at https://github.com/adobe/aio-cli-plugin-aem/blob/master/src/commands/aem/upload.js 
  - Replace instances of `DirectBinaryUploadOptions ` with `FileSystemUploadOptions` in upload.js 
```
        const uploadOptions = new FileSystemUploadOptions()
            .withUrl(`${trimRight(host, ['/'])}${target}`)
            .withBasicAuth(credential);
```
- Ensure an image exists in the root of the `aio-cli-plugin-aem` repo and run the upload command
  - E.g. `node bin/run aem:upload -h http://localhost:4502 -c admin:admin IMAGE_27547.jpg`

The console output indicates successful upload, and a folder was created in the root of /content/dam, but there is no image within the folder.

```

#### Platform and Version

#### Sample Code that illustrates the problem

#### Logs taken while reproducing problem

While debugging the upload result by placing a breakpoint at https://github.com/adobe/aio-cli-plugin-aem/blob/3a190e11478074b5afb27cccc2562364ec4a7f80/src/commands/aem/upload.js#L78 I get the following message:

Error: direct binary access not supported
    at DirectBinaryUploadProcess._callee2$ (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/@adobe/aem-upload/dist/direct-binary-upload-process.js:242:23)
    at tryCatch (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/@adobe/aem-upload/dist/direct-binary-upload-process.js:38:103)
    at _next (/Users/stewartleach/projects/isobar/source/aio-cli-plugin-aem/node_modules/@adobe/aem-upload/dist/direct-binary-upload-process.js:40:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by mfrisbey** [comment]
Thank you for the issue report.

> Note. I understand this code is designed to upload to the new adobe IO architecture of AEM Cloud, however, I'm assuming I can still use it to upload to none AEM Cloud versions

Unfortunately this assumption is incorrect. The library will only work AEM Cloud versions.
