### ISSUE TITLE
Upload a blob from nodeJs (server Side)

### ISSUE THREAD

**Issue by leandro-leroymerlin** [adobe/aem-upload#59]
Hi.

I need to upload an assets (image) from server to DAM, but for permissions, I can't create files in server (GCP pod).

When I try to upload a blob using DirectBinaryUploadOptions I recieve the following error:
`  message: 'TypeError: Expected a string, got undefined',
  stack: 'Error: TypeError: Expected a string, got undefined\n' +
    '    at C:\\Users\\Leandro\\Desktop\\ham\\gestionauditorias-api\\services\\aem-services.js:139:19\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
    '    at async uploadFileToAEM (C:\\Users\\Leandro\\Desktop\\ham\\gestionauditorias-api\\services\\aem-services.js:133:12)\n' +
    '    at async Object.uploadFile (C:\\Users\\Leandro\\Desktop\\ham\\gestionauditorias-api\\services\\aem-services.js:25:12)\n' +
    '    at async C:\\Users\\Leandro\\Desktop\\ham\\gestionauditorias-api\\api.js:66:80\n' +
    '    at async C:\\Users\\Leandro\\Desktop\\ham\\gestionauditorias-api\\api.js:21:11'
`

My code:
`const uploadFileToAEM = async (data) => {

    const {fileName, fileString, contentPath} = data;

    console.log(`uploading asset - URL: ${contentPath}, fileName: ${fileName}`)
    const {size, buffer} = b64toBuff(fileString);
    const arrayBuffer = toArrayBuffer(buffer)
    const arraybuffer = Uint8Array.from(buffer).buffer;

    const uploadFiles = [
        {
            fileName,
            fileSize: size,
            blob: arraybuffer ,
            replace: true,
        },
    ];

    const upload = new DirectBinary.DirectBinaryUpload();
    const options = new DirectBinary.DirectBinaryUploadOptions()
        .withUrl(contentPath)
        .withUploadFiles(uploadFiles)
        .withBasicAuth(`${environment.aemUsername}:${environment.aemPassword}`);

    monitorUploadEvents(upload, fileInServer);

    return await upload.uploadFiles(options)
        .then(result => {
            return result;
        })
        .catch(err => {
            //console.error('entro aqui', err)
            throw new Error(err)
        })
}`

Thanks for your help.

Regards

**Comment by mfrisbey** [comment]
The `TypeError` itself has been fixed with #61.

However, the README has also been updated to specify that the only tested and supported value for the `blob` option is that of an HTML `<input type="file" />`. We don't officially support the `blob` option through Node.JS. You're welcome to experiment to see if you can get it to work, but the recommendation is to use the `filePath` option when running Node.JS.
