### ISSUE TITLE
 code: 'EUNKNOWN',       innerStack: `Error: 'files' field missing in initiateUpload response:

### ISSUE THREAD

**Issue by Henry263** [adobe/aem-upload#60]
### Expected Behaviour

File should be uploaded.

### Actual Behaviour

code: 'EUNKNOWN',
      innerStack: `Error: 'files' field missing in initiateUpload response: [{"fileName”:”ascas-rasf-Pinouts.zip"}]\n` +
        '    at /Users/node-server-AEM-internal-ops/node_modules/@adobe/httptransfer/es2015/functions/aeminitiateupload.js:253:17\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at resume (/Users/node-server-AEM-internal-ops/node_modules/@adobe/httptransfer/es2015/functions/aeminitiateupload.js:108:362)\n' +
        '    at /Users//node-server-AEM-internal-ops/node_modules/@adobe/httptransfer/es2015/functions/aeminitiateupload.js:108:540\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
      uploadError: true

### Reproduce Scenario (including but not limited to)

I am using this code snippet from the example.

 try {
        // URL to the folder in AEM where assets will be uploaded. Folder
        // must already exist.
        const targetUrl = 'http://localhost:4502/content/dam/documents/temp';

        // list of all local files that will be uploaded.
        const uploadFiles = [{
            fileName: 'ascas-rasf-Pinouts.zip', // name of the file as it will appear in AEM
            fileSize: 10240, // total size, in bytes, of the file
            filePath: '/Users/docs/bulkupdate/ascas-rasf-Pinouts.zip' // Full path to the local file
        }];

        const upload = new DirectBinary.DirectBinaryUpload();
        const options = new DirectBinary.DirectBinaryUploadOptions()
            .withUrl(targetUrl)
            .withUploadFiles(uploadFiles)
            .withBasicAuth('admin:admin');

        upload.on('filestart', data => {
            const { fileName } = data;
            console.log("filestart", data);
            // specific handling that should occur when a file begins uploading
        });
        upload.on('fileprogress', data => {
            const { fileName, transferred } = data;
            console.log("fileprogress", data);

            // specific handling that should occur as a file uploads
        });
        upload.on('fileend', data => {
            const { fileName } = data;
            console.log("fileend", data);
            res.status('200').json({ "status": 200, "message": "file uploaded" });
            // specific handling that should occur when a file finishes uploading successfully
        });
        upload.on('fileerror', data => {
            const { fileName, errors } = data;
            console.log("fileerror", data);
            res.status('500').json({ "status": 500, "message": "Failed to upload files from file error" });

            // specific handling that should occur when a file files to upload
        });

        // assume options has been declared previously
        upload.uploadFiles(options);

    } catch (err) {
        console.log("8", err);
        //return { "status": err.response.status, "message": err.message };
        res.status('500').json({ "status": 500, "message": "Failed to upload files " });
    }

#### Steps to Reproduce
- Running on mac machine.
- Using Node js
- npm -v -> 6.13.4
- node -v -> v12.16.1
- In uploadfiles array I have only one file.
#### Sample Code that illustrates the problem
- Shared above
#### Logs taken while reproducing problem
- NA

**Comment by mfrisbey** [comment]
The reason for this error is that direct binary upload is not configured on the target AEM instance. See the [Background](https://github.com/adobe/aem-upload#background) information in the library's readme. The missing `files` field indicates that AEM's configuration is insufficient for using this library. We will update the message so that this is more clear.
