### ISSUE TITLE
Not able to upload asset on AEMaacs with given example 

### ISSUE THREAD

**Issue by vivekmalviya0104** [adobe/aem-upload#97]
Hello,
I am trying to use the sample code from Readme to test the upload an asset on AEM dev instance on cloud but it fails with the error below:

> received fileuploadstart
sending 1 files to httptransfer with options {
  "uploadFiles": [
    {
      "fileUrl": "https://author-pxxxxx-exxxxxx.adobeaemcloud.com/content/dam/upload/AdobeStock_434626222_Preview.jpeg",
      "fileSize": 437000,
      "filePath": "/path/to/test-images/AdobeStock_434626222_Preview.jpeg"
    }
  ],
  "headers": {
    "Content-Type": "image/jpeg",
    "Authorization": "Bearer <access_token_dev_instance>"
  },
  "concurrent": true,
  "maxConcurrent": 5
}
Waiting 273 milliseconds to attempt retry 1, failure: POST 'https://author-pxxxxx-exxxxx.adobeaemcloud.com/content/dam/upload.initiateUpload.json' failed with status 500:
....
....

> Closing all file handles
successfully uploaded files with httptransfer
Uploading result in JSON: {
    "host": "https://author-pxxxx-exxxxx.adobeaemcloud.com",
    "initSpent": 100,
    "totalFiles": 1,
    "totalTime": 24180,
    "totalCompleted": 1,
    "finalSpent": 24180,
    "totalFileSize": 437000,
    "avgFileSize": 437000,
    "avgPutSpent": 1000,
    "avgCompleteSpent": 200,
    "nintyPercentileTotal": 1200,
    "detailedResult": [
        {
            "fileName": "AdobeStock_434626222_Preview.jpeg",
            "targetPath": "/content/dam/upload/AdobeStock_434626222_Preview.jpeg",
            "fileSize": 437000,
            "partSize": 437000,
            "fileSizeStr": "426.76 KB",
            "partSizeStr": "426.76 KB",
            "partNum": 1,
            "putSpentFinal": 1000,
            "putSpentMin": 1000,
            "putSpentMax": 1000,
            "putSpentAvg": 1000,
            "completeSpent": 200,
            "success": true,
            "message": "",
            "partDetails": [
                {
                    "start": 0,
                    "end": 437000,
                    "message": "",
                    "elapsedTime": 1000,
                    "retryErrors": []
                }
            ],
            "retryErrors": []
        }
    ],
    "errors": [],
    "retryErrors": []
}
received fileuploadend
Results:{"fileName":"AdobeStock_434626222_Preview.jpeg","targetPath":"/content/dam/upload/AdobeStock_434626222_Preview.jpeg","fileSize":437000,"partSize":437000,"fileSizeStr":"426.76 KB","partSizeStr":"426.76 KB","partNum":1,"putSpentFinal":1000,"putSpentMin":1000,"putSpentMax":1000,"putSpentAvg":1000,"completeSpent":200,"success":true,"message":"","partDetails":[{"start":0,"end":437000,"message":"","elapsedTime":1000,"retryErrors":[]}],"retryErrors":[]}

**when checking in the AEM error.log, I see this error:**

> 

> *WARN*  POST /content/dam/upload.initiateUpload.json HTTP/1.1] com.adobe.granite.metrics.knownerrors.impl.ErrorLoggingComponentFilter Exception in component: category=ADOBE_UNKNOWN, resourceType=sling:Folder, exceptionType=java.lang.IllegalArgumentException, errorId=SLING_FOLDER, resource=/content/dam/upload, exceptionMessage = Missing field: fileName
*ERROR* POST /content/dam/upload.initiateUpload.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IllegalArgumentException: Missing field: fileName
	at com.adobe.cq.assetcompute.impl.servlet.ServletHelper.getStringParameters(ServletHelper.java:78) [com.adobe.cq.dam.cq-dam-processor-nui:1.1.726]
....
....

**Sample Code:**
`const DirectBinary = require('@adobe/aem-upload')

const access_token = <dev_access_token>
const targetUrl =
  'https://author-pxxxxx-exxxxxx.adobeaemcloud.com/content/dam/upload'

const uploadFiles = [
  {
    fileName: 'AdobeStock_434626222_Preview.jpeg',
    fileSize: 437000,
    filePath:
      '/path/to/test-images/AdobeStock_434626222_Preview.jpeg'
  }
]
const upload = new DirectBinary.DirectBinaryUpload({
  log: {
    debug: (...theArguments) => console.log.apply(null, theArguments),
    info: (...theArguments) => console.log.apply(null, theArguments),
    warn: (...theArguments) => console.log.apply(null, theArguments),
    error: (...theArguments) => console.log.apply(null, theArguments)
  }
})
const options = new DirectBinary.DirectBinaryUploadOptions()
  .withHeaders({
    'Content-Type': 'image/jpeg',
    Authorization: 'Bearer ' + access_token
  })
  .withUrl(targetUrl)
  .withUploadFiles(uploadFiles)

upload.on('fileuploadstart', event => {
  console.log('received fileuploadstart')
})

upload.on('fileuploadend', event => {
  console.log('received fileuploadend')
})

upload
  .uploadFiles(options)
  .then(result => {
    console.log('Results:' + result.getFileUploadResults())
    console.log('****************************************')
    // or retrieve individual file errors
    result.getFileUploadResults().forEach(fileResult => {
      fileResult.getErrors().forEach(fileErr => {
        if (fileErr.getCode() === codes.ALREADY_EXISTS) {
          const fileName = fileResult.getFileName()
          console.log(fileName + ' already exists')
        }
      })
    })
  })
  .catch(err => {
    if (err.getCode() === codes.NOT_SUPPORTED) {
      console.log(err.getCode() + 'Not Supported')
    } 
  })
`
Could you please let me know if I am missing something here ?

**Comment by vivekmalviya0104** [comment]
Hello, any update on this ?

**Comment by mfrisbey** [comment]
@vivekmalviya0104, please remove the `Content-Type` header in the `withHeaders()` call. That header should not be provided.

**Comment by vivekmalviya0104** [comment]
@mfrisbey , thanks a lot for your response. without header Content-Type, it uploads the files when the filePath is defined.
but is it possible to use the blob option while fetching the image via REST call and then upload it to AEM Cloud instance ? I tried but after upload to AEM, the status is set to Process Failed and there is no renditions generated in AEM.
